pull_request_rules:
  - name: "Merge when CI success"
    conditions:
      - author=jatcwang
      - status-success="build"
      - label=merge-when-ci-success
    actions:
      merge:
        method: merge
        #strict: smart+fasttrack
  - name: automatic merge for scala-steward pull requests affecting build.sbt
    conditions:
      - author=scala-steward
      - status-success="build"
      - "#files=1"
      - files=build.sbt
    actions:
      merge:
        method: merge
        #strict: smart+fasttrack
  - name: automatic merge for scala-steward pull requests affecting project plugins.sbt
    conditions:
      - author=scala-steward
      - status-success="build"
      - "#files=1"
      - files=project/plugins.sbt
    actions:
      merge:
        method: merge
        #strict: smart+fasttrack
  - name: semi-automatic merge for scala-steward pull requests
    conditions:
      - author=scala-steward
      - status-success="build"
    actions:
      merge:
        method: merge
        #strict: smart+fasttrack
  - name: automatic merge for scala-steward pull requests affecting project build.properties
    conditions:
      - author=scala-steward
      - status-success="build"
      - "#files=1"
      - files=project/build.properties
    actions:
      merge:
        method: merge
        #strict: smart+fasttrack
  - name: automatic merge for scala-steward pull requests affecting .scalafmt.conf
    conditions:
      - author=scala-steward
      - status-success="build"
      - "#files=1"
      - files=.scalafmt.conf
    actions:
      merge:
        method: merge
#        strict: smart+fasttrack
