pull_request_rules:
  - name: automatic merge for scala-steward pull requests affecting build.sbt
    conditions:
      - author=jatcwang
      - status-success="CI / test (pull_request)"
      - "#files=1"
      - files=build.sbt
    actions:
      merge:
        method: merge
  - name: automatic merge for scala-steward pull requests affecting project plugins.sbt
    conditions:
      - author=scala-steward
      - status-success="CI / test (pull_request)"
      - "#files=1"
      - files=project/plugins.sbt
    actions:
      merge:
        method: merge
  - name: semi-automatic merge for scala-steward pull requests
    conditions:
      - author=scala-steward
      - status-success="CI / test (pull_request)"
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: automatic merge for scala-steward pull requests affecting project build.properties
    conditions:
      - author=scala-steward
      - status-success="CI / test (pull_request)"
      - "#files=1"
      - files=project/build.properties
    actions:
      merge:
        method: merge
  - name: automatic merge for scala-steward pull requests affecting .scalafmt.conf
    conditions:
      - author=scala-steward
      - status-success="CI / test (pull_request)"
      - "#files=1"
      - files=.scalafmt.conf
    actions:
      merge:
        method: merge
