name: Release
on:
  push:
    branches: ["master"]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: openjdk@1.11
      - name: coursier cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier
          key: ${{ runner.OS }}-coursier-cache-${{ matrix.scala }}-${{ hashFiles('**/*.sbt') }} # -${{ hashFiles('project/**.scala') }} (fails for now)
          restore-keys: |
            ${{ runner.OS }}-coursier-cache-${{ matrix.scala }}-${{ hashFiles('**/*.sbt') }}-
            ${{ runner.OS }}-coursier-cache-${{ matrix.scala }}-
            ${{ runner.OS }}-coursier-cache-
      - name: Pull postgres image
        run: docker ps && docker pull postgres:12.3-alpine
      - uses: olafurpg/setup-gpg@v2
      - name: Publish ${{ github.ref }}
        run: sbt test ci-release publishMicrosite
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          GITHUB_TOKEN: {{ secrets.GITHUB_TOKEN }}
